image: 
  name: alpine/helm
  entrypoint: [""]

stages:
  - test
  - validate
  - plan
  - apply
  - destroy

before_script:
  - echo $GCP_SERVICE_ACCOUNT_KEY > gcloud-service-key.json

test:
  stage: test
  image: google/cloud-sdk
  script:
    - echo $CI_PROJECT_DIR
    - ls
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $GCP_PROJECT_ID

# validate:
#   stage: validate
#   script:
#     - helm repo add bitnami https://charts.bitnami.com/bitnami
#     - helm repo update
#     - helm repo list

# plan:
#   stage: plan
#   script:
#     - gitlab-terraform plan $(if [[ "$TF_DESTROY" == "true" ]]; then echo '-destroy'; fi)
#     - gitlab-terraform plan-json $(if [[ "$TF_DESTROY" == "true" ]]; then echo '-destroy'; fi)
#   artifacts:
#     name: plan
#     paths:
#       - ${TF_ROOT}/plan.cache
#     reports:
#       terraform: ${TF_ROOT}/plan.json

# apply:
#   stage: apply
#   rules:
#     - if: '$TF_DESTROY == "true"'
#       when: never
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#   script:
#     - gitlab-terraform apply
#   dependencies:
#     - plan
#   needs:
#     - plan

# destroy:
#   stage: destroy
#   rules:
#     - if: '$TF_DESTROY == "true"'
#   script:
#     - gitlab-terraform destroy
#   dependencies:
#     - plan
#   needs:
#     - plan