image: 
  name: alpine/helm
  entrypoint: [""]

stages:
  - test
  - validate
  - plan
  - apply
  - destroy

before_script:
  - echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json

test:
  stage: test
  image: google/cloud-sdk
  script:
    - echo $CI_PROJECT_DIR
    - ls
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $GCP_PROJECT_ID
    - gcloud projects list
    - curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    - sudo apt-get install apt-transport-https --yes
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    - sudo apt-get update
    - sudo apt-get install helm
    - helm repo add bitnami https://charts.bitnami.com/bitnami

# validate:
#   stage: validate
#   script:
#     - helm repo add bitnami https://charts.bitnami.com/bitnami
#     - helm repo update
#     - helm repo list

# plan:
#   stage: plan
#   script:
#     - gitlab-terraform plan $(if [[ "$TF_DESTROY" == "true" ]]; then echo '-destroy'; fi)
#     - gitlab-terraform plan-json $(if [[ "$TF_DESTROY" == "true" ]]; then echo '-destroy'; fi)
#   artifacts:
#     name: plan
#     paths:
#       - ${TF_ROOT}/plan.cache
#     reports:
#       terraform: ${TF_ROOT}/plan.json

# apply:
#   stage: apply
#   rules:
#     - if: '$TF_DESTROY == "true"'
#       when: never
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#   script:
#     - gitlab-terraform apply
#   dependencies:
#     - plan
#   needs:
#     - plan

# destroy:
#   stage: destroy
#   rules:
#     - if: '$TF_DESTROY == "true"'
#   script:
#     - gitlab-terraform destroy
#   dependencies:
#     - plan
#   needs:
#     - plan