image: 
  name: google/cloud-sdk
  entrypoint: [""]

stages:
  - initiate

before_script:
  - echo $GCLOUD_SERVICE_KEY > gcloud-service-key.json

initiate:
  stage: initiate
  script:
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $GCP_PROJECT_ID
    - gcloud projects list
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    - helm repo add kubeflow https://alauda.github.io/kubeflow-chart
    - helm repo update
    - helm repo list
    - kubectl get ns
    - kubectl create ns $K8S_NS 
    - kubectl get ns
    - helm install my-kubeflow kubeflow/kubeflow --version 1.6.2 -n $K8S_NS
    - helm ls -n $K8S_NS
    - kubectl get all -n $K8S_NS